### ISSUE TITLE
error while updating person: HHH000346: Error during managed flush

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#281]
while updating people i got a lot of error with the same error (and with various person , not the same) 
[28.03.2016 23:24:58] ERROR org.hibernate.internal.SessionImpl  - HHH000346: Error during managed flush [Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1]
[28.03.2016 23:24:58] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Failed storing person filmography 12031-'Paul Anderson'
[28.03.2016 23:24:58] ERROR org.yamj.core.service.metadata.MetadataScannerService  - Storage error
org.springframework.orm.hibernate5.HibernateOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:206)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:741)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:589)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.yamj.core.database.service.MetadataStorageService$$EnhancerBySpringCGLIB$$825acabf.updateScannedPersonFilmography(<generated>)
	at org.yamj.core.service.metadata.MetadataScannerService.scanFilmography(MetadataScannerService.java:209)
	at org.yamj.core.service.metadata.MetadataScannerService.processQueueElement(MetadataScannerService.java:68)
	at org.yamj.core.scheduling.QueueProcessRunner.run(QueueProcessRunner.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
	at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3106)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2985)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3365)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:145)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:560)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:434)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1295)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:468)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3135)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2352)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:485)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:147)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:581)
	... 14 more

**Comment by jluc2808** [comment]
[yamj-core.ERROR.txt](https://github.com/YAMJ/yamj-v3/files/192514/yamj-core.ERROR.txt)
add error_log

**Comment by modmax** [comment]
It seems, that several threads (metadatascan, people scan, filmo scan) are acting on the same objects, so that the database state differs between the threads and therefore the database produces such errors, cause. This can occure if Thread A and B fetch the same person at the same time, but thread A finishes and stores the person in the database and afterwards tThread B wants to store the person, but then has an older version as expected to store (cause Thread B will not actualizy it's person when person is stored by Thread B),

This behaviour can occur everytime, cause the system wants to get informations in the database, but sometime it may fail, expecially if multiple threads are used.

Normally such errors should clean up themselves, cause objecs with locking problems will be retried.

**Comment by modmax** [comment]
In case of locking problem due several threads, which changed the same objects, just a warning should be displayed and the object should then stay in the same state.

Due to missing exception handling for hibernate5 locking error, those errors has been handled as normal errors and the object was set to ERROR instead of leaving them in the previous state.

The exception handling has been fixed, so that the desired effect of not changing the state and reprocess that objects should take place.

The as ERROR marked objects can be set to UPDATED via SQL-Update-Script.

**Comment by modmax** [comment]
Here are the updates per SQL:

update person set status='UPDATED' where status='ERROR';
update person set filmography_status='UPDATED' where filmography_status='ERROR';
update videodata set status='UPDATED' where status='ERROR';
update season set status='UPDATED' where status='ERROR';
update series set status='UPDATED' where status='ERROR';

**Comment by jluc2808** [comment]
do you think adding an ERRORSanity task give sense ? (which could perform all sql change you mentionned above)

**Comment by modmax** [comment]
No .. cause the ERRORness objects will be rechecked after 7 days; perhaps then the problem is solved.

The update statements here has just been added to fix the database, cause there was a bug in the core ... but that's no general issue.

**Comment by AkashShukla199** [comment]
I am still facing this issue while bulk record processing
HHH000346: Error during managed flush [Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.jbpm.persistence.processinstance.ProcessInstanceInfo#189388]]
